-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 24-06-2026 a las 17:40:15
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `ovni_db`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `avistamientos`
--

CREATE TABLE `avistamientos` (
  `id` int(11) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `lat` float NOT NULL,
  `lng` float NOT NULL,
  `año` int(11) NOT NULL,
  `pais` varchar(255) NOT NULL,
  `ciudad` varchar(100) DEFAULT '',
  `descripcion` text NOT NULL,
  `imagenes` text NOT NULL,
  `video` varchar(500) NOT NULL,
  `tipo` varchar(50) DEFAULT 'orbe'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `avistamientos`
--

INSERT INTO `avistamientos` (`id`, `nombre`, `lat`, `lng`, `año`, `pais`, `ciudad`, `descripcion`, `imagenes`, `video`, `tipo`) VALUES
(1, 'Magenta', 45.4642, 8.884, 1933, 'Italia', 'Magenta, Milán', 'El caso OVNI de Magenta relata la caída de un objeto volador no identificado en Italia en 1933, durante el gobierno de Benito Mussolini.\r\nSegún la historia, el régimen fascista recuperó el objeto y lo investigó en secreto mediante un grupo llamado RS/33.', '', '', 'platillo'),
(2, 'Trinity', 33.917, -106.86, 1945, 'Estados Unidos', 'San Antonio, Nuevo México', 'El caso Trinity es un incidente OVNI ocurrido en 1945 cerca de San Antonio, en Nuevo México, poco después de la primera prueba nuclear Trinity.\r\nDos niños afirmaron haber visto un objeto extraño estrellado y pequeños seres cerca del lugar del impacto.', '', '', 'platillo'),
(3, 'Phoenix Lights', 33.4484, -112.074, 1997, 'Estados Unidos', 'Phoenix, Arizona', '\r\nEl 13 de marzo de 1997, miles de testigos en Phoenix, Arizona, y en todo el estado de Nevada presenciaron una formación de luces que se desplazaba lentamente en silencio a baja altitud. Las luces formaban un arco o triángulo gigante y permanecieron visibles durante más de dos horas. El gobernador Fife Symington reconoció años después haber visto personalmente el objeto. Es uno de los avistamientos con mayor número de testigos de la historia.\r\n', 'uploads/1779567494_3027ee3c-aacb-45bb-815f-a5db39110898_2560x1440.jpg', 'https://www.youtube.com/embed/CvkfbqhNc6w', 'luces'),
(4, 'Nimitz FLIR1', 32.5, -117.5, 2004, 'Estados Unidos', 'Océano Pacífico', 'En noviembre de 2004, pilotos de la Armada de EE.UU. a bordo del portaaviones USS Nimitz detectaron durante varios días objetos aéreos no identificados en el radar del USS Princeton. El comandante David Fravor se aproximó a uno de ellos: describió un objeto blanco con forma de tic-tac de unos 12 metros que aceleraba de forma imposible. El vídeo FLIR1 fue desclasificado oficialmente por el Pentágono en abril de 2020.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/US_Navy_F-18_FLIR_UFO.jpg/640px-US_Navy_F-18_FLIR_UFO.jpg', 'https://www.youtube.com/embed/PBLI4O3CP5c', 'cigarro'),
(5, 'McMinnville', 45.2101, -123.199, 1950, 'Estados Unidos', 'McMinnville, Oregón', 'El 11 de mayo de 1950, el granjero Paul Trent y su esposa fotografiaron un objeto metálico que sobrevolaba su propiedad en McMinnville, Oregón. Las dos fotografías fueron analizadas por el Comité Condon de la Universidad de Colorado y por investigadores de Stanford, quienes no encontraron evidencias de manipulación. El ángulo de iluminación, las sombras y la perspectiva resultaron consistentes con un objeto real de gran tamaño a distancia considerable.', 'https://upload.wikimedia.org/wikipedia/commons/8/89/Trent_UFO_Photos.jpg', 'https://www.youtube.com/embed/GaELrJEHaHs', 'platillo'),
(6, 'Rendlesham Forest', 52.0937, 1.4413, 1980, 'Reino Unido', 'Suffolk', 'Entre el 26 y el 28 de diciembre de 1980, personal militar de la base de la RAF Woodbridge en Suffolk presenció una serie de luces inexplicables en el bosque de Rendlesham. El teniente coronel Charles Halt realizó una grabación de audio durante el segundo avistamiento. Los testigos describieron un objeto triangular de unos 3 metros con luces de colores que dejó marcas en el suelo y elevados niveles de radiación. Conocido como el \"Roswell británico\".', 'uploads/1779567842_4542.avif,uploads/1779567847_Rendlesham_Forest_UFO_Sculpture_-_geograph.org.uk_-_8120767.jpg', 'https://www.youtube.com/embed/iqowZQ61pdA', 'triangulo'),
(7, 'Ola OVNI Belga', 50.5039, 4.4699, 1990, 'Bélgica', 'Lieja, Bélgica', 'Entre 1989 y 1990, más de 13.500 personas en Bélgica reportaron avistamientos de triángulos negros silenciosos con tres luces blancas en los vértices y una roja central. La noche del 30 al 31 de marzo de 1990, dos cazas F-16 de la Fuerza Aérea Belga detectaron el objeto en radar y lo persiguieron. El objeto realizó maniobras imposibles para la tecnología de la época: aceleró de 280 a 1.800 km/h en un segundo y descendió de 3.000 a 1.500 metros de altitud bruscamente.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Belgian_UFO_wave_triangle_night.jpg/640px-Belgian_UFO_wave_triangle_night.jpg,https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Belgian_black_triangle_UFO.jpg/400px-Belgian_black_triangle_UFO.jpg', 'https://www.youtube.com/embed/pSfZgRgqHzU', 'triangulo'),
(8, 'Lubbock Lights', 33.5779, -101.855, 1951, 'Estados Unidos', 'Lubbock, Texas', 'En agosto y septiembre de 1951, varios profesores de la Universidad Tecnológica de Texas presenciaron repetidamente formaciones de 20 a 30 luces que cruzaban el cielo nocturno de Lubbock en perfecta formación semicircular. El estudiante Carl Hart Jr. fotografió una de estas formaciones con su cámara. El Proyecto Blue Book de la USAF investigó el caso y lo clasificó como \"desconocido\". Las fotos de Hart resistieron múltiples análisis sin que se detectara manipulación.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Lubbock_lights_carlhart.jpg/640px-Lubbock_lights_carlhart.jpg', 'https://www.youtube.com/embed/EZmgMkFYBU0', 'luces'),
(9, 'Roswell', 33.3943, -104.523, 1947, 'Estados Unidos', 'Roswell, Nuevo México', 'En julio de 1947, algo cayó en un rancho cerca de Roswell, Nuevo México. El mayor Jesse Marcel del 509.º Grupo Bombardero recuperó los restos y declaró inicialmente que se trataba de un \"disco volante\". El ejército retractó esa versión horas después, atribuyéndolo a un globo meteorológico. Décadas de investigación, testimonios de personal militar y documentos desclasificados han alimentado la teoría de que el gobierno recuperó uno o más vehículos no terrestres y cuerpos de sus tripulantes.', '', 'https://www.youtube.com/embed/RU9SHoSRMB8', 'platillo'),
(10, 'JAL 1628', 61.2181, -149.9, 1986, 'Estados Unidos', 'Anchorage, Alaska', 'El 17 de noviembre de 1986, la tripulación del vuelo de carga Japan Airlines 1628 reportó el avistamiento de tres objetos luminosos sobre Alaska durante unos 50 minutos. El capitán Kenju Terauchi describió el objeto principal como \"enorme, el doble que un portaaviones\", con dos naves más pequeñas de acompañamiento. El control de tráfico aéreo de Anchorage y un avión de la USAF que pasaba por la zona también detectaron ecos en sus radares.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/JAL1628drawing.jpg/640px-JAL1628drawing.jpg', 'https://www.youtube.com/embed/7vj0bZnQHfk', 'platillo'),
(11, 'GO FAST', 28, -80.5, 2015, 'Estados Unidos', 'Costa de Florida', 'En 2015, pilotos de la Armada de EE.UU. del USS Theodore Roosevelt grabaron este vídeo sobre el Atlántico frente a la costa de Florida. El objeto se mueve a velocidad muy baja a gran altitud según el HUD, pero el cálculo real indica una velocidad de más de 400 km/h al nivel del agua. El vídeo fue desclasificado por el Departamento de Defensa en 2020, confirmando su autenticidad. Los pilotos reportaron ver estos objetos casi a diario durante meses.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/GO_FAST_UAP_video_screenshot.jpg/640px-GO_FAST_UAP_video_screenshot.jpg', 'https://www.youtube.com/embed/wxCjLMVVRSE', 'orbe'),
(12, 'O\'Hare', 41.9742, -87.9073, 2006, 'Estados Unidos', 'Chicago, Illinois', 'El 7 de noviembre de 2006, entre las 16:15 y las 16:30 hora local, al menos doce empleados de United Airlines —personal de tierra y pilotos— observaron un objeto gris metálico con forma de disco estacionado en las nubes sobre la puerta C17 del aeropuerto internacional O\'Hare de Chicago. El objeto permanecía completamente inmóvil antes de dispararse verticalmente a gran velocidad, dejando un agujero circular en la capa de nubes. La FAA atribuyó el avistamiento a un \"vórtice de viento\", explicación que la tripulación rechazó.', '', 'https://www.youtube.com/embed/NnCOd-j_CnA', 'platillo'),
(13, 'Socorro', 34.0584, -106.891, 1964, 'Estados Unidos', 'Socorro, Nuevo México', 'El 24 de abril de 1964, el agente de policía Lonnie Zamora perseguía un vehículo por la carretera cuando escuchó un rugido y vio una llama azulada. Investigando, encontró un objeto ovalado blanco apoyado sobre patas en el terreno, junto al cual había dos figuras de aspecto humano pero de pequeño tamaño con trajes blancos. El objeto despegó verticalmente con estrépito y desapareció. El investigador del Proyecto Blue Book, Hector Quintanilla, declaró que era el caso más sólido e inexplicable que había investigado.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Zamora_UFO_drawing.jpg/400px-Zamora_UFO_drawing.jpg', 'https://www.youtube.com/embed/gU_53gMeHdc', 'orbe'),
(14, 'Levelland', 33.5873, -102.379, 1957, 'Estados Unidos', 'Levelland, Texas', 'La noche del 2 al 3 de noviembre de 1957, al menos ocho conductores en las carreteras alrededor de Levelland, Texas, reportaron que sus motores y faros se apagaban al aproximarse a un objeto luminoso alargado posado en la carretera. El objeto era descrito como una bala o torpedo de unos 60 metros, de color rojo brillante. Cuando el objeto despegaba, los vehículos volvían a funcionar con normalidad. El sheriff Weir Clem y dos de sus ayudantes también lo vieron desde distintos puntos de la ciudad.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Levelland_ufo_case_diagram.jpg/400px-Levelland_ufo_case_diagram.jpg', 'https://www.youtube.com/embed/5n3Bk2Wiqb8', 'cigarro'),
(15, 'Kenneth Arnold', 46.8523, -121.76, 1947, 'Estados Unidos', 'Monte Rainier, Washington', 'El 24 de junio de 1947, el piloto privado Kenneth Arnold divisó nueve objetos brillantes en formación cerca del monte Rainier, Washington. Los describió como platillos que se desplazaban a unos 2.700 km/h. El término \"platillo volante\" nació de la cobertura periodística de su relato. Este avistamiento dio inicio a la era moderna de los OVNI.', '', '', 'platillo'),
(16, 'Washington D.C.', 38.9072, -77.0369, 1952, 'Estados Unidos', 'Washington D.C.', 'Durante las noches del 19 al 20 y del 26 al 27 de julio de 1952, el radar del aeropuerto Nacional de Washington y el de Andrews AFB detectaron múltiples objetos no identificados sobrevolando la capital federal, incluyendo la zona restringida sobre la Casa Blanca. Pilotos de la USAF enviados a interceptar describieron luces que los \"jugaban al gato y al ratón\". El evento generó la mayor rueda de prensa del Pentágono desde la Segunda Guerra Mundial.', '', '', 'luces'),
(17, 'Kecksburg', 40.1837, -79.4609, 1965, 'Estados Unidos', 'Kecksburg, Pensilvania', 'El 9 de diciembre de 1965, miles de personas en varios estados y Canadá vieron cruzar el cielo un objeto luminoso. En Kecksburg, Pensilvania, testigos describieron un objeto con forma de bellota —de unos 3 metros de diámetro— semienterrado en el bosque, con marcas similares a jeroglíficos en su base. El ejército acordonó la zona y se retiró con un objeto cubierto en camión. La NASA afirmó años después que era un meteorito soviético, pero nunca mostró restos.', '', '', 'orbe'),
(18, 'Cash-Landrum', 30.1824, -95.2571, 1980, 'Estados Unidos', 'Huffman, Texas', 'El 29 de diciembre de 1980, Betty Cash, Vickie Landrum y su nieto Colby presenciaron en la carretera de Huffman, Texas, un objeto romboidal incandescente rodeado de helicópteros CH-47 Chinook militares. Las tres personas sufrieron quemaduras graves, pérdida de cabello y síntomas consistentes con irradiación. Cash fue hospitalizada repetidamente. Demandaron al gobierno federal, que negó la propiedad del objeto; el caso fue desestimado.', '', '', 'cigarro'),
(19, 'Trans-en-Provence', 43.6047, 1.4442, 1981, 'Francia', 'Var, Francia', 'El 8 de enero de 1981, el agricultor Renato Nicolaï presenció en su finca de Trans-en-Provence el aterrizaje de un objeto circular que dejó marcas circulares en el suelo. El GEPAN —grupo oficial del CNES— analizó las muestras de tierra y plantas del lugar y encontró cambios bioquímicos inexplicables: reducción de clorofila y alteraciones en la composición mineral del suelo. El informe oficial francés clasificó el caso como \"evento físico real de origen desconocido\".', '', '', 'platillo'),
(20, 'Stephenville', 32.2207, -98.2023, 2008, 'Estados Unidos', 'Stephenville, Texas', 'El 8 de enero de 2008, docenas de personas en Stephenville y Erath County, Texas, reportaron ver un objeto enorme de luces blancas seguido por cazas de la USAF. El objeto, descrito como del tamaño de un campo de fútbol americano, voló sin sonido. La USAF negó inicialmente tener aviones en la zona, para admitir días después que sí había F-16 realizando maniobras. El MUFON analizó datos de radar de la FAA que confirmaron ecos anómalos hacia la Casa de Camp David.', '', '', 'luces'),
(21, 'Frederick Valentich', 38.9333, 143.4, 1978, 'Australia', 'Estrecho de Bass', 'El 21 de octubre de 1978, el piloto australiano Frederick Valentich de 20 años sobrevolaba el estrecho de Bass en su Cessna 182L cuando reportó por radio que un objeto brillante lo estaba siguiendo y le pasaba por encima a alta velocidad. Describió un cilindro metálico que \"no era una aeronave\". A los cuatro minutos de transmisión, se escuchó un ruido metálico raspante y la comunicación se cortó. Valentich y su avión nunca fueron encontrados.', '', '', 'cigarro'),
(22, 'Shag Harbour', 43.4656, -65.7378, 1967, 'Canadá', 'Shag Harbour, Nueva Escocia', 'El 4 de octubre de 1967, múltiples testigos en Shag Harbour, Nueva Escocia, vieron cuatro luces naranja-amarillas parpadear en secuencia y luego sumergirse en el océano con un destello. La Real Policía Montada de Canadá y pescadores locales buscaron restos en el agua. El informe oficial canadiense lo calificó como \"objeto desconocido de origen no determinado\". Es uno de los pocos casos OVNI con investigación gubernamental oficial abierta.', '', '', 'luces'),
(23, 'Teherán', 35.6892, 51.389, 1976, 'Irán', 'Teherán', 'El 19 de septiembre de 1976, dos cazas F-4 Phantom de la Fuerza Aérea Imperial Iraní fueron enviados a interceptar un objeto brillante sobre Teherán. Cuando los pilotos intentaron disparar, sus sistemas de armas quedaron inutilizados. Cuando se alejaban, los sistemas recuperaban la función. Un informe interno del DIA estadounidense calificó el incidente como \"un clásico ejemplo de avistamiento de OVNI en el que todos los elementos —aeronave hostil, interferencia electrónica, luz cegadora— estuvieron presentes\".', '', '', 'orbe'),
(24, 'Travis Walton', 34.3917, -110.025, 1975, 'Estados Unidos', 'Snowflake, Arizona', 'El 5 de noviembre de 1975, el leñador Travis Walton desapareció durante cinco días en los bosques de Apache-Sitgreaves, Arizona, frente a seis compañeros que describieron haberle visto alcanzado por un rayo azul proveniente de un objeto luminoso. Walton reapareció en estado de desorientación y describió un interior de nave con tripulantes no humanos. Sus compañeros superaron pruebas poligráficas. El caso fue adaptado al cine en Fire in the Sky (1993).', '', '', 'orbe'),
(25, 'Kaikoura', -42.3988, 173.682, 1978, 'Nueva Zelanda', 'Kaikoura', 'El 31 de diciembre de 1978, el equipo de televisión australiano de Channel 0 filmó desde un avión de carga sobre Kaikoura varios objetos luminosos brillantes que los acompañaban durante el vuelo. Las imágenes en color de 16mm fueron analizadas por el físico Bruce Maccabee del Naval Surface Weapons Center, quien descartó reflexiones, venus u otros fenómenos convencionales. Es uno de los avistamientos filmados mejor documentados del siglo XX.', '', '', 'orbe'),
(26, 'Ariel School', -18.1896, 31.5497, 1994, 'Zimbabwe', 'Ruwa, Mashonaland', 'El 16 de septiembre de 1994, más de 60 niños de la escuela primaria Ariel en Ruwa, Zimbabwe, salieron al recreo y presenciaron el aterrizaje de un objeto plateado en el campo adyacente. Describieron uniformemente figuras pequeñas de ojos grandes junto al objeto. El investigador de Harvard John Mack entrevistó a los niños por separado y concluyó que los testimonios eran coherentes y genuinos. Los adultos no estaban en el patio en ese momento.', '', '', 'platillo'),
(27, 'Colares', -0.9342, -47.5701, 1977, 'Brasil', 'Isla Colares, Pará', 'Entre agosto y octubre de 1977, los habitantes de la isla Colares en Pará, Brasil, fueron víctimas de ataques de haces de luz que provenían de objetos voladores. Varias personas resultaron heridas con marcas circulares, quemaduras y pérdida de sangre. La Fuerza Aérea Brasileña lanzó la Operación Prato bajo las órdenes del capitán Uyrangê Hollanda, quienes fotografiaron y filmaron los objetos. Los documentos fueron desclasificados parcialmente en 2004 y Hollanda declaró públicamente antes de morir que los objetos eran reales.', '', '', 'cigarro'),
(28, 'Gütersloh', 51.9069, 8.3808, 1990, 'Alemania', 'Gütersloh', 'Durante la ola OVNI belga de 1989-1990, testigos en el noroeste de Alemania también reportaron triángulos negros silenciosos. La base aérea de la OTAN en Gütersloh, Renania del Norte-Westfalia, recibió múltiples informes de personal militar que vio objetos triangulares sobrevolando el perímetro. La Bundeswehr nunca publicó una explicación oficial.', '', '', 'triangulo'),
(29, 'Petit-Rechain', 50.639, 5.859, 1990, 'Bélgica', 'Petit-Rechain, Bélgica', 'En abril de 1990, en plena ola OVNI belga, el fotógrafo Patrick Ferryn capturó en Petit-Rechain una imagen de un triángulo oscuro con tres luces brillantes en los vértices y una central más grande rojiza. La fotografía fue analizada durante años por la Sociedad Belga de Estudios de Fenómenos Aéreos Espaciales (SOBEPS). En 2011 el autor confesó que era un montaje, lo que no explicó los miles de avistamientos de testigos oculares del período.', '', '', 'triangulo'),
(30, 'Canal de la Mancha', 49.5, -2.2, 2007, 'Reino Unido', 'Jersey, Canal de la Mancha', 'El 23 de abril de 2007, los pilotos de dos vuelos comerciales —un Aurigny y un Blue Islands— informaron a los controladores aéreos de Jersey de un enorme objeto brillante sobre el canal de la Mancha. Ambos lo describieron como una masa de luz amarilla de cientos de metros de longitud que se dividía en dos. Los radares de Jersey no registraron ningún eco, pero los controladores confirmaron que los pilotos estaban claramente nerviosos.', '', '', 'cigarro'),
(31, 'Villareal', 39.9369, -0.1006, 1979, 'España', 'Villarreal, Castellón', 'El 6 de noviembre de 1979, el capitán del buque mercante Monte Urgull, Francisco Javier Lerdo de Tejada, y su tripulación observaron durante dos horas varios objetos luminosos que rodearon su barco frente a Valencia. Uno de los objetos descendió hasta casi la superficie del mar. El caso fue investigado por el CESID y la Armada Española. España es uno de los países que desclasificó archivos OVNI oficiales, incluyendo este expediente.', '', '', 'luces'),
(32, 'Talavera la Real', 38.8333, -6.7667, 1980, 'España', 'Badajoz', 'El 5 de febrero de 1980, el cabo José María Trejo y el soldado Juan Carrizosa, de guardia en la base aérea de Talavera la Real (Badajoz), observaron una esfera de luz brillante de gran tamaño que se aproximó a la base y se detuvo sobre la pista. Trejo fue encontrado inconsciente y con quemaduras. El expediente fue investigado por el Ejército del Aire y posteriormente desclasificado. Es uno de los casos más documentados de la ufología española.', '', '', 'orbe'),
(33, 'Canarias', 28.1235, -15.4363, 1976, 'España', 'Islas Canarias', 'El 22 de junio de 1976, miles de personas en las Islas Canarias presenciaron una esfera azulada traslúcida y luminosa de enorme tamaño que sobrevolaba el archipiélago. Dentro se distinguían dos figuras humanas. El destructor Atrevida de la Armada también lo observó. El Ministerio del Aire investigó el caso y el expediente fue desclasificado en 1994. Es considerado el caso OVNI más importante de la historia española.', '', '', 'orbe'),
(34, 'Colunga', 43.4813, -5.2757, 1983, 'España', 'Colunga, Asturias', 'El 12 de mayo de 1983, el guardia civil Julio Rey, destinado en Colunga, Asturias, observó un objeto plateado con forma de sombrero de copa a escasos metros de distancia mientras patrullaba. El objeto emitía un zumbido suave y proyectaba luz pulsante. Al alejarse, dejó una marca circular quemada en el suelo. El informe oficial del Cuerpo de la Guardia Civil fue incluido en los archivos desclasificados por el Ministerio de Defensa español.', '', '', 'platillo'),
(35, 'Aluche', 40.378, -3.7281, 1979, 'España', 'Madrid', 'El 23 de agosto de 1979, el piloto Juan De La Vega de vuelo comercial sobrevolando el área de Aluche, Madrid, reportó a la torre de control de Barajas un objeto triangular de grandes dimensiones sin luces de posición que se desplazaba en dirección norte a velocidad imposible. Los controladores no detectaron nada en radar. El caso está incluido en los expedientes desclasificados por el Ejército del Aire en 1994.', '', '', 'triangulo'),
(36, 'Hessdalen', 62.8, 11.1833, 1982, 'Noruega', 'Valle de Hessdalen', 'Desde finales de 1981, el valle de Hessdalen en el centro de Noruega se convirtió en el escenario de avistamientos frecuentes de luces inexplicables: bolas de luz amarilla, blanca y roja de comportamiento errático. El Proyecto Hessdalen, iniciado en 1983, es el estudio científico continuado más largo sobre fenómenos luminosos no identificados. Aún activo hoy, ha documentado miles de eventos y los científicos no han llegado a un consenso sobre su naturaleza.', '', '', 'orbe'),
(37, 'Petrozavodsk', 61.7892, 34.3469, 1977, 'Rusia', 'Petrozavodsk, Carelia', 'El 20 de septiembre de 1977, a las 4:00 de la madrugada, los habitantes de Petrozavodsk en Carelia (URSS) vieron un objeto brillante en el cielo que proyectaba rayos en abanico hacia la tierra \"como una medusa luminosa\". El fenómeno duró unos 10-12 minutos y fue registrado también en Helsinki, Leningrado y Riga. La agencia TASS lo reportó oficialmente. La comunidad científica soviética no llegó a una conclusión definitiva.', '', '', 'luces'),
(38, 'Vorónezh', 51.6694, 39.1919, 1989, 'Rusia', 'Vorónezh', 'El 27 de septiembre de 1989, varios niños y adultos en un parque de Vorónezh, Rusia, presenciaron el aterrizaje de un objeto esférico enorme. De él descendieron dos o tres figuras de entre 3 y 4 metros de altura. La agencia TASS informó del caso, lo que causó sensación mundial. La policía local y científicos del Comité de Investigación Geofísica analizaron el lugar y encontraron marcas en el terreno.', '', '', 'orbe'),
(39, 'Imjärvi', 60.3167, 24.8, 1970, 'Finlandia', 'Imjärvi, Finlandia', 'El 7 de enero de 1970, los esquiadores Aarno Heinonen y Esko Viljo presenciaron en el bosque de Imjärvi el descenso de un objeto circular que emitía un haz de luz rojo. Una figura pequeña con un traje brillante surgió del haz. Ambos sufrieron síntomas físicos graves durante semanas: náuseas, dolores de cabeza y parálisis momentánea. El caso fue investigado por la Junta de Investigación OVNI de Finlandia.', '', '', 'platillo'),
(40, 'Baia Mare', 47.6667, 23.5833, 1968, 'Rumanía', 'Baia Mare, Rumanía', 'En agosto de 1968, el médico Florin Gheorghita presenció y fotografió un objeto metalico circular en el cielo de Baia Mare. El caso fue investigado por la Academia de Ciencias de Rumanía. Rumanía fue uno de los países del bloque del Este con mayor actividad ufológica documentada durante la Guerra Fría, con informes de la Securitate sobre avistamientos en zonas militares.', '', '', 'platillo'),
(41, 'Trindade', -20.5167, -29.3333, 1958, 'Brasil', 'Isla Trindade', 'El 16 de enero de 1958, a bordo del barco oceanográfico Almirante Saldanha de la Marina de Brasil frente a la isla de Trindade, el fotógrafo Almiro Baraúna capturó cuatro fotografías de un objeto toroi deo que sobrevolaba la isla ante la vista de unos 150 tripulantes. La Marina Brasileña certificó la autenticidad de las fotos. El presidente Juscelino Kubitschek autorizó la publicación de las imágenes.', '', '', 'platillo'),
(42, 'Mendoza', -32.8908, -68.8272, 1986, 'Argentina', 'Mendoza', 'El 31 de julio de 1986, un objeto brillante fue rastreado durante varias horas por el radar del aeropuerto de Mendoza y observado por varios pilotos. La Fuerza Aérea Argentina abrió una investigación formal. Argentina posee uno de los pocos organismos gubernamentales del mundo dedicados oficialmente al estudio de OVNI: el CEFAE, creado en 2011.', '', '', 'orbe'),
(43, 'Linares', -36.3833, -71.5333, 1975, 'Chile', 'Linares', 'En junio de 1975, varios campesinos en la provincia de Linares, Chile, reportaron objetos luminosos que descendían cerca de la cordillera. La Fuerza Aérea de Chile investigó el caso. Chile estableció en 1997 el CEFAA (Comité de Estudios de Fenómenos Aéreos Anómalos), organismo oficial que ha publicado decenas de informes verificados con respaldo de pilotos y controladores aéreos.', '', '', 'luces'),
(44, 'Asunción', -25.2867, -57.647, 1965, 'Paraguay', 'Asunción', 'En octubre de 1965, múltiples testigos en Asunción y alrededores reportaron una serie de objetos luminosos que cruzaban el cielo nocturno durante varias noches consecutivas. Uno de los objetos sobrevoló el aeropuerto de Presidente Stroessner y fue detectado brevemente en radar. El gobierno paraguayo no emitió declaración oficial.', '', '', 'luces'),
(45, 'São Paulo Lights', -23.5505, -46.6333, 1996, 'Brasil', 'São Paulo', 'El 22 de mayo de 1996, cientos de testigos en el gran São Paulo vieron luces en formación cruzar el cielo nocturno. El evento fue grabado en vídeo por varios vecinos y emitido en los telediarios brasileños. La Fuerza Aérea Brasileña afirmó que podría tratarse de desechos de un cohete en reentrada, pero la trayectoria no era consistente con dicha hipótesis.', '', '', 'luces'),
(46, 'Lima', -12.0464, -77.0428, 2007, 'Perú', 'Lima', 'En octubre de 2007, el canal peruano Frecuencia Latina emitió imágenes grabadas desde el centro de Lima de un objeto metálico que permanecía estacionario durante horas. La DIRANDRO y la Fuerza Aérea del Perú iniciaron una investigación. El coronel FAP Oscar Ugarte declaró que el objeto no figuraba en ningún plan de vuelo y no pudo ser identificado.', '', '', 'orbe'),
(47, 'Arica', -18.4783, -70.3126, 2000, 'Chile', 'Arica', 'En abril de 2000, pilotos y controladores del aeropuerto Chacalluta de Arica reportaron un objeto de gran tamaño que sobrevolaba la costa norte de Chile durante varios minutos. El CEFAA recopiló los testimonios y los datos de radar. El caso fue uno de los primeros publicados en los informes anuales del CEFAA.', '', '', 'platillo'),
(48, 'Varginha', -21.5514, -45.4292, 1996, 'Brasil', 'Varginha, Minas Gerais', 'En enero de 1996, varios residentes de Varginha, Minas Gerais, reportaron haber visto una o más criaturas de aspecto inusual en distintos puntos de la ciudad. El Ejército Brasileño desplegó efectivos en la zona. Algunos testigos afirmaron que los militares capturaron al menos una de las criaturas. El caso generó una enorme cobertura mediática en Brasil y es conocido como el \"Roswell brasileño\".', 'uploads/1779567255_tvqb92v6as8g1.jpeg', 'https://www.youtube.com/embed/ZHKjpahsVHA', 'orbe'),
(49, 'JAL Pacífico', 35.6762, 139.65, 1974, 'Japón', 'Tokio', 'En el verano de 1974, la tripulación de un vuelo de Japan Airlines sobre el Pacífico describió una esfera de luz de gran diámetro que se mantuvo paralela a su ruta durante más de 20 minutos antes de desaparecer en vertical. El caso fue recogido en los informes internos de JAL y más tarde por el investigador Richard Haines.', '', '', 'orbe'),
(50, 'Tokio', 35.6762, 139.65, 1975, 'Japón', 'Tokio', 'En diciembre de 1975, varios agentes de la Policía Metropolitana de Tokio en diferentes distritos reportaron simultáneamente un objeto brillante que permanecía estacionario sobre la ciudad a gran altitud antes de desplazarse hacia el norte a velocidad muy alta. La Agencia de Defensa Japonesa no publicó comentario oficial.', '', '', 'platillo'),
(51, 'Seúl', 37.5665, 126.978, 1980, 'Corea del Sur', 'Seúl', 'En septiembre de 1980, pilotos de la Fuerza Aérea de Corea del Sur reportaron el seguimiento de un objeto no identificado en maniobras durante un ejercicio conjunto con EE.UU. La historia fue confirmada en una entrevista años después por un piloto retirado surcoreano al canal de investigación KBS.', '', '', 'triangulo'),
(52, 'Teherán', 35.6892, 51.389, 2004, 'Irán', 'Teherán', 'En enero de 2004, durante varios días, residentes de distintas ciudades iraníes reportaron objetos luminosos. Pilotos de la Fuerza Aérea Islámica de Irán fueron enviados a interceptar sin conseguir aproximarse. El gobierno iraní emitió una advertencia advirtiendo a la población de no disparar contra los objetos.', '', '', 'luces'),
(53, 'Hangzhou', 39.3434, 117.362, 2010, 'China', 'Hangzhou', 'El 11 de julio de 2010, el aeropuerto internacional de Hangzhou fue cerrado durante una hora después de que un objeto luminoso sobrevolara la pista. Más de 18 vuelos sufrieron retrasos. El gobierno chino abrió una investigación y no publicó conclusiones. Dos semanas después se repitió el cierre en el aeropuerto de Baotou, Mongolia Interior.', '', '', 'cigarro'),
(54, 'Dalnegorsk', 44.5569, 135.569, 1986, 'Rusia', 'Dalnegorsk, Primorie', 'El 29 de enero de 1986, un objeto esférico rojo cruzó el pueblo de Dalnegorsk a baja altitud y se estrelló en la colina llamada \"Height 611\". Equipos de rescate encontraron vidrio metálico, hilos de material desconocido y virutas con alta proporción de metales raros. El material fue enviado a varios institutos soviéticos. El análisis de la Academia de Ciencias de la URSS describió los restos como de composición no convencional.', '', '', 'orbe'),
(55, 'Pekín', 39.9042, 116.407, 1999, 'China', 'Pekín', 'La madrugada del 24 de junio de 1999 —aniversario del caso Arnold— cientos de personas en Pekín vieron una luz brillante en espiral cruzar el cielo nocturno. Fue fotografiada desde varias partes de la ciudad. El gobierno chino lo atribuyó a un cohete experimental, pero no presentó pruebas. Desde 1978 China tiene grupos de investigación OVNI vinculados a universidades.', '', '', 'luces'),
(56, 'El Cairo', 30.0444, 31.2357, 2009, 'Egipto', 'El Cairo', 'En octubre de 2009, decenas de testigos en distintas zonas de El Cairo reportaron un objeto luminoso que permanecía estático sobre la ciudad durante más de 30 minutos. El evento fue grabado por varios ciudadanos y las imágenes circularon en los medios árabes. La Fuerza Aérea egipcia no hizo declaraciones.', '', '', 'orbe'),
(57, 'Pretoria', -26.2041, 28.0473, 1965, 'Sudáfrica', 'Pretoria', 'En octubre de 1965, el funcionario Johan Hamman fotografió en Pretoria un objeto metálico plateado con forma de disco. Las fotografías fueron analizadas por la Junta de Investigación de la Fuerza de Defensa de Sudáfrica, que emitió un informe clasificado. El caso fue revisado por el investigador Cynthia Hind, considerada la principal ufóloga de África.', '', '', 'platillo'),
(58, 'Kalahari', -23, 23.5, 1989, 'Botswana', 'Desierto del Kalahari', 'El 7 de mayo de 1989, según fuentes sudafricanas filtradas, un objeto no identificado fue derribado por dos cazas Mirage de la SAAF en el desierto del Kalahari en territorio de Botswana. Supuestamente la USAF intervino para hacerse con los restos. El Ministerio de Defensa de Sudáfrica negó el incidente. Parte de los documentos fue publicada por investigadores, pero su autenticidad no ha podido verificarse.', '', '', 'platillo'),
(59, 'Tully', -17.9333, 145.917, 1966, 'Australia', 'Tully, Queensland', 'El 19 de enero de 1966, el agricultor George Pedley presenció en un pantano de Tully, Queensland, cómo un objeto gris azulado de unos 8 metros ascendía del agua con un silbido. Dejó en el agua un circulo perfecto de juncos aplastados en espiral de unos 9 metros de diámetro. Es el primer caso documentado de \"crop circle\" en agua. Las autoridades no dieron explicación.', '', '', 'platillo'),
(60, 'Westall', -37.9267, 145.117, 1966, 'Australia', 'Melbourne, Victoria', 'El 6 de abril de 1966, más de 200 estudiantes y profesores del colegio Westall High School en Clayton Sur, Melbourne, presenciaron un disco plateado que descendió a un campo cercano, estuvo posado brevemente y luego ascendió velozmente. Cinco avionetas civiles lo persiguieron. Las autoridades intimidaron a los testigos para que guardaran silencio. Ningún avión pudo identificarse.', '', '', 'platillo'),
(61, 'Kaikoura', -42.4, 173.967, 1978, 'Nueva Zelanda', 'Kaikoura', 'En la noche del 20 al 21 de diciembre de 1978, la tripulación y el equipo de televisión a bordo de un Argosy de Safe Air grabaron sobre la costa de Kaikoura objetos luminosos de gran tamaño. Las imágenes en 16mm fueron sometidas a análisis por el físico Bruce Maccabee y por la División de Fotografía del Departamento de Defensa de Nueva Zelanda, que no pudo dar una explicación satisfactoria.', '', '', 'orbe'),
(62, 'Fátima', 39.6186, -8.6737, 1917, 'Portugal', 'Fátima', 'El 13 de octubre de 1917, ante una multitud estimada entre 30.000 y 100.000 personas reunidas en Fátima, Portugal, se produjo el llamado \"Milagro del Sol\": un objeto luminoso giró sobre sí mismo, descendió en espiral y emitió luces de colores antes de elevarse. Investigadores ufológicos como Jacques Vallée y J. Allen Hynek han señalado el paralelismo con descripciones OVNI contemporáneas. Los testigos estaban secos minutos después de haber estado bajo la lluvia.', '', '', 'luces'),
(63, 'Flatwoods', 38.7262, -80.6534, 1952, 'Estados Unidos', 'Flatwoods, Virginia Occ.', 'El 12 de septiembre de 1952, seis jóvenes y una adulta en Flatwoods, Virginia Occidental, siguieron una luz que creyeron era un meteorito y encontraron en la colina un objeto pulsante y una figura de más de 3 metros con forma de as de picas, que emitía un gas sulfuroso. Varios de los testigos sufrieron irritación de garganta y ojos durante semanas. Investigadores del Proyecto Blue Book visitaron el lugar.', '', '', 'orbe'),
(64, 'Caso Gorman', 46.8083, -96.7698, 1948, 'Estados Unidos', 'Fargo, Dakota del Norte', 'El 1 de octubre de 1948, el teniente George Gorman de la Guardia Nacional Aérea de Dakota del Norte persiguió durante 27 minutos una pequeña luz blanca sobre Fargo. La luz realizó maniobras imposibles para los aviones de la época: giraba, ascendía y aceleraba de forma abrupta. El Proyecto Sign lo clasificó como \"desconocido\" y no llegó a una conclusión.', '', '', 'orbe'),
(65, 'British Airways', 50, -30, 1991, 'Reino Unido', 'Atlántico Norte', 'El 21 de enero de 1991, los pilotos del vuelo Speedbird 5068 de British Airways reportaron cómo un objeto triangular iluminado pasó a escasos metros de su avión sobre el Atlántico Norte. Los pilotos lo describieron como un misil antes de ver que no llevaba propulsión aparente. El incidente fue reportado a la Autoridad de Aviación Civil Británica.', '', '', 'triangulo'),
(66, 'Manises', 39.4893, -0.4722, 1979, 'España', 'Valencia', 'El 11 de noviembre de 1979, el vuelo Iberia IB-297 procedente de Salzburgo realizó un aterrizaje de emergencia en el aeropuerto de Manises, Valencia, después de que su tripulación reportara luces que se aproximaban peligrosamente. Dos cazas F-1 de la base de Los Llanos fueron enviados a interceptar. El teniente coronel Celestino Carrasco describió un objeto romboi deo que realizó maniobras evasivas. El caso está en los archivos desclasificados del Ejército del Aire.', 'uploads/1779566801_1257799622_0.jpg,uploads/1779566806_www.mallorcadiario.com__fotos_1_471092_pep-climent-soller-ovni.webp', 'https://www.youtube.com/embed/RIiUWknYw5w', 'luces'),
(67, 'Puerto Rico', 18.2566, -66.1057, 1987, 'Estados Unidos', 'Aguadilla, Puerto Rico', 'El 28 de diciembre de 1987, cientos de testigos en el noroeste de Puerto Rico presenciaron el enfrentamiento entre cazas F-14 de la Armada y objetos luminosos que se sumergieron en el lago Cartagena y el océano. El fenómeno se repitió en distintas noches. La base de Ramey y la estación naval de Roosevelt Roads tenían actividad inusual. Jorge Martín, principal investigador ufológico de Puerto Rico, recopiló más de 2.000 testimonios de la zona entre 1987 y 1994.', '', '', 'orbe'),
(68, 'Berlín', 52.52, 13.405, 1952, 'Alemania', 'Berlín', 'En julio de 1952, en plena ola OVNI mundial, pilotos aliados sobre Berlín Occidental reportaron objetos luminosos a gran altitud. Los radares de la USAF en Rhein-Main registraron ecos anómalos. El incidente coincidió con la ola de Washington DC y fue incluido en los informes del Proyecto Blue Book como parte del análisis de la ola de 1952.', '', '', 'luces'),
(69, 'Lac Chauvet', 45.33, 2.99, 1952, 'Francia', 'Auvernia, Francia', 'El 18 de julio de 1952, el geólogo André Frégnale fotografió un disco metálico sobre el lago Chauvet en Auvernia. La imagen fue analizada por el Comité Científico de Fenómenos Aeroespaciales del CNES, que concluyó que era un objeto de material metálico sólido.', '', '', 'platillo'),
(70, 'Valensole', 43.8356, 5.9828, 1965, 'Francia', 'Valensole, Provenza', 'El 1 de julio de 1965, el agricultor Maurice Masse encontró en su campo de lavanda en Valensole, Provenza, un objeto ovalado con patas y dos figuras de pequeño tamaño que lo observaban. Al verle, lo inmovilizaron con un objeto y despegaron. El GEPAN analizó el suelo décadas después y encontró alteraciones similares a las del caso Trans-en-Provence.', '', '', 'platillo'),
(71, 'Piana degli Albanesi', 37.9925, 13.2844, 1978, 'Italia', 'Sicilia, Italia', 'En diciembre de 1978, durante la ola italiana de avistamientos conocida como la \"Ola del 78\", una familia en Piana degli Albanesi, Sicilia, fotografió un objeto con forma de sombrero chino luminoso. El investigador Roberto Pinotti del Centro Ufologico Nazionale (CUN) analizó el caso.', '', '', 'platillo'),
(72, 'Balwyn', -37.8399, 145.072, 1966, 'Australia', 'Melbourne, Victoria', 'El 2 de abril de 1966, el ingeniero James Kibel fotografió en Melbourne un objeto gris metálico con forma de disco. Las fotos fueron analizadas por el RAAF y por el Comité Consultivo Científico OVNI de Melbourne, que las consideró auténticas.', '', '', 'platillo'),
(73, 'Araraquara', -21.785, -48.1786, 1986, 'Brasil', 'Araraquara, São Paulo', 'El 19 de mayo de 1986, la Fuerza Aérea Brasileña lanzó la denominada \"Noche Oficial Brasileña de OVNI\": más de 20 objetos no identificados saturaron los radares de Brasilia, São Paulo y el ministerio de Aeronáutica. Ocho cazas F-5 y Mirage fueron enviados a interceptar durante varias horas sin éxito. El ministro de Aeronáutica, Brigadeiro Octávio Júlio Moreira Lima, confirmó públicamente los hechos al día siguiente.', '', '', 'orbe'),
(74, 'Hessdalen', 62.83, 11.2, 1984, 'Noruega', 'Valle de Hessdalen', 'En enero-febrero de 1984, el equipo del Proyecto Hessdalen capturó en vídeo una bola de luz brillante estática sobre el valle. El físico Erling Strand calculó un diámetro de entre 20 y 30 metros. Los instrumentos del observatorio midieron durante el evento campos electromagnéticos anómalos. La Universidad de Östersund mantiene activa una cámara automática en el valle.', '', '', 'orbe'),
(75, 'Villaverde', 40.3456, -3.7012, 1968, 'España', 'Madrid', 'En la noche del 31 al 1 de febrero de 1968, varios vecinos del barrio madrileño de Villaverde reportaron un objeto luminoso grande que descendió y se estacionó sobre los tejados durante varios minutos. Fue visible también desde Getafe. El informe fue recogido por la Guardia Civil y posteriormente catalogado en los archivos desclasificados del Ejército del Aire español.', '', '', 'platillo'),
(76, 'Loch Raven Dam', 39.4748, -76.5488, 1958, 'Estados Unidos', 'Maryland', 'El 26 de octubre de 1958, dos hombres que pescaban cerca de la presa de Loch Raven en Maryland vieron un enorme objeto oval estático a unos 75 metros sobre el puente. Su coche se detuvo. Sintieron calor intenso y el objeto despegó con un destello y gran estrépito. Fueron examinados en el hospital con síntomas de quemadura solar. El caso fue investigado por el Proyecto Blue Book.', '', '', 'cigarro'),
(77, 'Livingston', 55.891, -3.5231, 1979, 'Reino Unido', 'West Lothian, Escocia', 'El 9 de noviembre de 1979, el trabajador forestal Robert Taylor sufrió lo que describió como un ataque de dos objetos esféricos con protuberancias metálicas mientras caminaba en Dechmont Law, West Lothian. Encontraron marcas en el suelo y en sus pantalones consistentes con un tirón mecánico. La Policía de Lothian y Borders abrió una investigación criminal —única en el mundo por un avistamiento OVNI— que nunca se cerró.', '', '', 'orbe'),
(78, 'Greifswald', 54.0955, 13.3816, 1990, 'Alemania', 'Greifswald', 'En la noche del 24 de agosto de 1990, decenas de testigos en Greifswald, en la antigua Alemania del Este, observaron una formación de esferas luminosas que se reagrupaban sobre el mar Báltico. Muchos de los testigos eran científicos del cercano centro nuclear. El astrónomo checo Jan Rajchl analizó el evento y lo publicó en 1992.', '', '', 'luces'),
(79, 'Holloman AFB', 32.851, -106.106, 1955, 'Estados Unidos', 'Alamogordo, Nuevo México', 'En mayo de 1955, personal de la base aérea de Holloman en Nuevo México reportó el aterrizaje de un objeto sobre la pista. La historia fue corroborada por el productor Robert Emenegger, quien afirmó que el Pentágono le prometió imágenes fílmicas del aterrizaje para un documental de 1974 antes de retirar la oferta. Varios empleados lo declararon antes de morir.', '', '', 'platillo'),
(80, 'Trancas', -26.2167, -65.3333, 1963, 'Argentina', 'Trancas, Tucumán', 'El 21 de octubre de 1963, la familia Moreno en la estancia \"La Rubia\" de Trancas, Tucumán, Argentina, presenció el posado de varios objetos circulares iluminados en el campo. Un haz de luz barrió la casa. Varias integrantes de la familia sufrieron síntomas físicos. Es considerado el caso OVNI mejor documentado de Argentina y fue recogido en el informe APRO.', '', '', 'platillo'),
(81, 'Ubatuba', -23.4336, -45.0838, 1957, 'Brasil', 'Ubatuba, São Paulo', 'En septiembre de 1957, el periodista Ibrahim Sued recibió fragmentos de un material que, según su informante, provenían de un objeto que había explotado sobre la bahía de Ubatuba. El material fue analizado en el laboratorio del Brasil Atomic Energy Commission y la Universidad del Estado de Nueva York: los resultados indicaron magnesio de pureza inusual. El análisis de 1967 por el Comité Condon sugirió que podría ser de fabricación terrestre no convencional.', '', '', 'platillo'),
(82, 'San Luis Potosí', 22.1565, -100.985, 1994, 'México', 'San Luis Potosí', 'El 8 de agosto de 1994, el piloto aficionado Carlos de los Santos fue seguido por tres objetos durante su aproximación al aeropuerto de Ciudad de México. Uno de ellos quedó enganchado bajo su avión, provocando que los controles no respondieran. Cuando los objetos se alejaron, recuperó el control. El Centro de Investigación Aeronáutica del Departamento de Aeronáutica Civil investigó el caso.', '', '', 'orbe'),
(83, 'Cohetes Fantasma', 59.3293, 18.0686, 1946, 'Suecia', 'Suecia central', 'En el verano de 1946, Suecia registró cientos de avistamientos de objetos luminosos alargados denominados \"cohetes fantasma\". Los militares suecos recibieron más de 2.000 informes entre mayo y diciembre. El misterio preocupó a los aliados, que temían fuesen misiles soviéticos derivados del V-2. Más del 20% de los casos no pudieron explicarse por fenómenos meteorológicos.', '', '', 'cigarro'),
(84, 'La Palma', 28.6835, -17.7642, 2021, 'España', 'La Palma, Canarias', 'El 23 de septiembre de 2021, durante la erupción del volcán Cumbre Vieja en La Palma, cámaras de vigilancia de los medios de comunicación captaron objetos luminosos no identificados que sobrevolaban la columna de lava. El INVOLCAN y la Agencia Estatal de Meteorología descartaron drones y relámpagos de ceniza para varios de los objetos. Las imágenes circularon ampliamente en redes sociales.', '', '', 'luces'),
(85, 'Aguadilla', 18.4273, -67.1541, 2013, 'Estados Unidos', 'Aguadilla, Puerto Rico', 'En mayo de 2013, una cámara FLIR de un avión de la Aduana y Protección Fronteriza de EE.UU. grabó sobre Aguadilla, Puerto Rico, un objeto que volaba a gran velocidad, se sumergía en el océano, avanzaba bajo el agua y volvía a emerger. El vídeo fue obtenido mediante FOIA y analizado por el Scientific Coalition for UAP Studies, que no encontró explicación convencional.', '', '', 'orbe'),
(86, 'Calvine', 56.85, -3.8, 1990, 'Reino Unido', 'Perthshire, Escocia', 'En agosto de 1990, dos excursionistas fotografiaron en Calvine, Perthshire, un objeto de diamante metálico de gran tamaño acompañado de un avión militar. Las fotos fueron entregadas al Daily Record, que las cedió al Ministerio de Defensa. Permanecieron clasificadas durante 32 años; en 2022 el investigador Dr. David Clarke obtuvo que la RAF las liberara. Las imágenes muestran claramente un objeto grande de geometría no convencional.', '', '', 'platillo'),
(87, 'Socorro II', 34.0584, -106.891, 1965, 'Estados Unidos', 'Socorro, Nuevo México', 'En los meses posteriores al caso Zamora, otros testigos reportaron objetos similares aterrizando en los alrededores de Socorro, Nuevo México. El investigador del Proyecto Blue Book visitó de nuevo la localidad y documentó tres avistamientos adicionales que guardaban similitud con el primero.', '', '', 'orbe'),
(88, 'Portage County', 41.1767, -81.1846, 1966, 'Estados Unidos', 'Ohio', 'La madrugada del 17 de abril de 1966, el agente Dale Spaur y su compañero persiguieron durante 80 km una luz brillante que volaba a baja altura sobre las autopistas de Ohio y Pensilvania. Otros agentes se unieron a la persecución. El objeto ascendió finalmente y desapareció. El Proyecto Blue Book lo atribuyó al satélite Echo y a Venus, versión que los pilotos y agentes rechazaron públicamente.', '', '', 'orbe'),
(89, 'Teide', 28.2725, -16.6421, 2016, 'España', 'Tenerife, Canarias', 'El 5 de noviembre de 2016, cámaras del observatorio del Teide en Tenerife captaron un objeto luminoso que cruzaba el cielo a gran velocidad durante el seguimiento de un meteorito. El vídeo fue publicado por el Instituto de Astrofísica de Canarias, que no descartó la posibilidad de que fuera un satélite, pero señaló que la trayectoria no coincidía con ningún objeto catalogado.', '', '', 'orbe'),
(90, 'El Hierro', 27.7415, -17.922, 2004, 'España', 'El Hierro, Canarias', 'En julio de 2004, pescadores y residentes de la isla de El Hierro reportaron luces que emergían del mar en la costa de Orchilla durante varias noches. La Guardia Civil recogió los testimonios. El fenómeno coincidió con actividad volcánica submarina. Los testigos describieron los objetos como esferas naranja que subían verticalmente.', '', '', 'luces'),
(91, 'Torrejón de Ardoz', 40.4578, -3.459, 1975, 'España', 'Madrid', 'En octubre de 1975, personal de guardia de la base aérea de Torrejón de Ardoz, Madrid, observó un objeto luminoso de gran tamaño estacionado sobre los alrededores de la base durante más de una hora. El radar de la base registró brevemente un eco anómalo. El informe fue clasificado y posteriormente incluido en los expedientes desclasificados del Ejército del Aire.', '', '', 'platillo'),
(92, 'Rota', 36.6198, -6.3507, 1979, 'España', 'Rota, Cádiz', 'El 3 de noviembre de 1979, pocas semanas antes del caso Manises, personal de la base naval de Rota en Cádiz reportó un objeto luminoso que sobrevoló las instalaciones durante varios minutos a baja altitud. El incidente fue recogido en los expedientes clasificados conjuntos de la Armada española y la US Navy.', '', '', 'luces'),
(93, 'Cieza', 38.2385, -1.4181, 1978, 'España', 'Cieza, Murcia', 'En octubre de 1978, vecinos de Cieza y de la comarca del Segura, Murcia, presenciaron durante varias noches consecutivas objetos de luz variable que realizaban maniobras sobre la sierra del Molino. La Guardia Civil recibió decenas de denuncias. El caso fue investigado por el periodista ufólogo Juan José Benítez y publicado en su libro de 1982.', '', '', 'luces'),
(94, 'Figueres', 42.267, 2.9604, 1968, 'España', 'Figueres, Girona', 'El 22 de agosto de 1968, el médico Eduardo Sesma y su familia observaron en la comarca del Alt Empordà, Girona, un objeto plateado en rotación que descendió hasta unos 100 metros de altura. El caso fue comunicado al Centro de Investigaciones OVNI de España y recogido en los archivos del Ejército del Aire.', '', '', 'platillo'),
(95, 'Cascais', 38.6979, -9.4215, 1999, 'Portugal', 'Cascais, Lisboa', 'En septiembre de 1999, varios testimonios de pescadores en la costa de Cascais describieron un objeto triangular negro que sobrevolaba el estuario del Tajo a baja altura con luces en los vértices. El Gabinete Português de Estudo dos Fenómenos Aeroespaciais recopiló los testimonios.', '', '', 'triangulo'),
(96, 'Cap d\'Antibes', 43.5672, 7.1278, 1967, 'Francia', 'Antibes, Francia', 'En septiembre de 1967, varios marineros en el Mediterráneo frente a la Costa Azul reportaron un objeto cilíndrico luminoso que emergió del mar y ascendió verticalmente a gran velocidad. El caso fue registrado por el Marine Nationale francés y posteriormente estudiado por el GEPAN.', '', '', 'cigarro'),
(97, 'Val Bormida', 44.3833, 8.2833, 1978, 'Italia', 'Liguria, Italia', 'En diciembre de 1978, durante la ola italiana de avistamientos, varios agricultores del valle del Bórmida en Liguria describieron objetos con forma de cigarro plateado que sobrevolaban el valle por la noche. El CUN (Centro Ufologico Nazionale) abrió investigación.', '', '', 'cigarro'),
(98, 'Moscú', 55.7558, 37.6173, 1978, 'Rusia', 'Moscú', 'En septiembre de 1978, testigos en distintos puntos de Moscú, incluyendo personal del aeropuerto Sheremetyevo, reportaron un disco luminoso que se desplazó sobre la ciudad en dirección norte. El Ministerio del Interior soviético no emitió declaración.', '', '', 'platillo');
INSERT INTO `avistamientos` (`id`, `nombre`, `lat`, `lng`, `año`, `pais`, `ciudad`, `descripcion`, `imagenes`, `video`, `tipo`) VALUES
(99, 'Popocatépetl', 19.022, -98.6277, 2000, 'México', 'Puebla / Morelos', 'Desde el año 2000, las cámaras de vigilancia del volcán Popocatépetl han captado repetidamente objetos luminosos que entran y salen de la caldera. El Instituto Nacional de Investigaciones Nucleares, encargado del monitoreo, ha descartado meteoros y aviones en varios de los casos más llamativos. Los vídeos son públicos en la web del CENAPRED.', '', '', 'cigarro'),
(100, 'Aguascalientes', 21.8818, -102.292, 1994, 'México', 'Aguascalientes', 'El 11 de julio de 1994, durante el eclipse solar total visible desde México, cientos de observadores capturaron en vídeo objetos plateados sobrevolando distintas ciudades del país. Las imágenes de Aguascalientes fueron analizadas por Jaime Maussan y la NASA descartó que fueran artefactos ópticos del eclipse.', '', '', 'platillo');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `avistamientos`
--
ALTER TABLE `avistamientos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `avistamientos`
--
ALTER TABLE `avistamientos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=102;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
